# SPDX-FileCopyrightText: © 2020 Software in the Public Interest, Inc.
# SPDX-FileCopyrightText: © 2020 Martin Michlmayr <tbm@cyrius.com>
#
# SPDX-License-Identifier: GPL-2.0-or-later
language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - ledger
install:
  - pip install -r requirements.txt
script:
  - python -m pytest
