---
site_name: beancount2beancount
site_description: Beancount to Ledger converter
site_url: https://beancount2ledger.readthedocs.io/
repo_url: https://github.com/beancount/beancount2ledger
site_author: Martin Blais, Martin Michlmayr
use_directory_urls: true

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - shell
        - text
        - yaml

nav:
    - Introduction: index.md
    - Getting started:
          - Installation: install.md
          - Usage: usage.md
    - About:
          - Release notes: changelog.md
          - Bugs and contributions: contributing.md
          - Authors and contributors: authors.md
          - License and copyright: license.md

markdown_extensions:
    - toc:
          permalink: 
          baselevel: 2
    - def_list

plugins:
    - search
    - exclude:
          glob:
              - "*.1"
              - "*.5"
              - "*.scd"
