#!/bin/sh

# SPDX-FileCopyrightText: © 2020 Martin Michlmayr <tbm@cyrius.com>

# SPDX-License-Identifier: GPL-2.0-or-later

find -name "*.md" -exec aspell -d en -x --mode markdown --home-dir=. check {} \;

find -name "*.py" -exec codespell {} \;

find \( -name "*.md" -or -name "*.scd" \) -exec anorack {} \;

find \( -name "*.md" -or -name "*.scd" \) -exec codespell {} \;

